### ISSUE TITLE
capicator 2 support?

### ISSUE THREAD

**Issue by danielsigl** [robingenz/capacitor-firebase-performance#12]
**Is your feature request related to a problem? Please describe:**
use plugin with capicator 2

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment]
Thank you for your feature request.
Unfortunately, this plugin only supports Capacitor 3.
Since Capacitor 2 is now deprecated, no support will be added.
